// admin-react/src/views/admin/menu/components/SaveMenuModal.tsx
import { useEffect, useMemo, useState } from 'react';
import { Form, Input, InputNumber, Modal, Switch, TreeSelect, message } from 'antd';
import { addAdminMenu, editAdminMenu, getAdminMenuInfo } from '@/api/admin/menu';
import { AdminMenuKey, AdminRouterPath } from '@/api/pattern';
import { DefaultModalWidth } from '@/api/config';
import IconSelect from '@/components/IconSelect';
import type { MenuTreeItem, ReqAdminMenuAdd } from '@/types/admin_menu';

/** 把路径转为键名（大驼峰） */
function path2UpperCamelCase(path: string) {
  return path
    ?.split('/')
    .filter((name) => name.length > 0)
    .map((name) => name[0].toUpperCase() + name.substring(1))
    .join('');
}

interface SaveMenuModalProps {
  open: boolean;
  tree: MenuTreeItem[];
  detailData?: MenuTreeItem;
  onClose: () => void;
  onNotice: () => void;
}

/** 新建/编辑菜单（键名由路径自动生成，不可编辑） */
export default function SaveMenuModal(props: SaveMenuModalProps) {
  const { open, tree, detailData, onClose, onNotice } = props;
  const [form] = Form.useForm();
  const [confirmLoading, setConfirmLoading] = useState(false);

  const treeSelectData = useMemo(() => {
    interface SelectNode {
      key: number;
      value: number;
      title: string;
      children?: SelectNode[];
    }
    const build = (list: MenuTreeItem[]): SelectNode[] =>
      list.map((item) => ({
        key: item.id as number,
        value: item.id as number,
        title: item.name ?? '',
        children: item.children?.length ? build(item.children) : undefined,
      }));
    return [{ key: 0, value: 0, title: '顶级菜单' }, ...build(tree)];
  }, [tree]);  useEffect(() => {
    if (open) {
      if (detailData?.id) {
        // 编辑：实时拉取详情回填，避免编辑列表中的过期数据
        getAdminMenuInfo({ menuId: detailData.id }).then((res) => {
          const info = res.data as MenuTreeItem;
          form.setFieldsValue({
            parentId: info.parentId || 0,
            name: info.name || '',
            path: info.path || '',
            key: info.key || '',
            sort: info.sort ?? 0,
            icon: info.icon || '',
            redirect: info.redirect || '/',
            describe: info.describe || '',
            isHideInMenu: !!info.hideInMenu,
            isHideChildrenInMenu: !!info.hideChildrenInMenu,
            isEnabled: !!info.enabled,
          });
        });
      } else {
        form.resetFields();
        form.setFieldsValue({
          parentId: detailData?.parentId ?? 0,
          sort: 0,
          icon: '',
          redirect: '/',
          isHideInMenu: false,
          isHideChildrenInMenu: false,
          isEnabled: true,
        });
      }
    }
  }, [open, detailData, form]);

  // 键名由路径自动生成
  const onPathChange = (path: string) => {
    form.setFieldValue('key', path2UpperCamelCase(path));
  };

  const handleOk = async () => {
    const values = await form.validateFields();
    const data: ReqAdminMenuAdd & { id?: number } = { ...values, parentId: values.parentId ?? 0 };
    setConfirmLoading(true);
    try {
      const res = detailData?.id ? await editAdminMenu({ ...data, id: detailData.id }) : await addAdminMenu(data);
      message.success(res.msg, 2);
      onNotice();
      onClose();
    } finally {
      setConfirmLoading(false);
    }
  };

  return (
    <Modal open={open} title={detailData?.id ? '编辑菜单' : '新建菜单'} width={DefaultModalWidth} confirmLoading={confirmLoading} maskClosable={false} okText="保存" cancelText="取消" onOk={handleOk} onCancel={onClose}>
      <Form form={form} labelCol={{ span: 8 }} wrapperCol={{ span: 14 }}>
        <Form.Item label="父级菜单" name="parentId">
          <TreeSelect treeData={treeSelectData} treeDefaultExpandAll placeholder="请选择父级菜单" allowClear />
        </Form.Item>
        <Form.Item label="菜单名称" name="name" rules={[{ required: true, message: '请输入菜单名称' }, { max: 50, message: '菜单名称长度不能超过50个字符' }]}>
          <Input placeholder="请输入菜单名称" allowClear />
        </Form.Item>
        <Form.Item label="菜单路径" name="path" rules={[{ required: true, message: '请输入菜单路径' }, { pattern: AdminRouterPath, message: '路径格式不正确' }]}>
          <Input placeholder="请输入菜单路径" allowClear onChange={(e) => onPathChange(e.target.value)} />
        </Form.Item>
        <Form.Item label="键名" name="key" rules={[{ required: true, pattern: AdminMenuKey, message: '请按照驼峰法命名' }]}>
          <Input disabled placeholder="根据菜单路径自动生成" />
        </Form.Item>
        <Form.Item label="排序" name="sort">
          <InputNumber min={0} style={{ width: '100%' }} />
        </Form.Item>
        <Form.Item label="图标" name="icon">
          <IconSelect placeholder="请选择图标" />
        </Form.Item>
        <Form.Item label="重定向地址" name="redirect">
          <Input placeholder="请输入重定向地址" allowClear />
        </Form.Item>
        <Form.Item label="描述" name="describe">
          <Input placeholder="请输入菜单描述" allowClear />
        </Form.Item>
        <Form.Item label="是否隐藏菜单" name="isHideInMenu" valuePropName="checked">
          <Switch checkedChildren="隐藏" unCheckedChildren="显示" />
        </Form.Item>
        <Form.Item label="是否隐藏子菜单" name="isHideChildrenInMenu" valuePropName="checked">
          <Switch checkedChildren="隐藏" unCheckedChildren="显示" />
        </Form.Item>
        <Form.Item label="是否启用" name="isEnabled" valuePropName="checked">
          <Switch checkedChildren="启用" unCheckedChildren="禁用" />
        </Form.Item>
      </Form>
    </Modal>
  );
}

// admin-vue3x/src/views/admin/menu/components/SaveMenuModal.vue
<template>
  <a-modal
    :open="open"
    :title="detailData?.id ? '编辑菜单' : '新建菜单'"
    :width="DefaultModalWidth"
    :confirm-loading="confirmLoading"
    :mask-closable="false"
    ok-text="保存"
    cancel-text="取消"
    @ok="handleOk"
    @cancel="handleCancel"
  >
    <a-form ref="formRef" :model="formState" :rules="rules" :label-col="{ span: 8 }" :wrapper-col="{ span: 14 }">
      <a-form-item label="父级菜单" name="parentId">
        <a-tree-select
          v-model:value="formState.parentId"
          :tree-data="treeSelectData"
          tree-default-expand-all
          placeholder="请选择父级菜单"
          allow-clear
        />
      </a-form-item>
      <a-form-item label="菜单名称" name="name">
        <a-input v-model:value="formState.name" placeholder="请输入菜单名称" allow-clear />
      </a-form-item>
      <a-form-item label="菜单路径" name="path">
        <a-input v-model:value="formState.path" placeholder="请输入菜单路径" allow-clear @change="onPathChange" />
      </a-form-item>
      <a-form-item label="键名" name="key">
        <a-input v-model:value="formState.key" disabled />
      </a-form-item>
      <a-form-item label="排序" name="sort">
        <a-input-number v-model:value="formState.sort" :min="0" style="width: 100%" />
      </a-form-item>
      <a-form-item label="图标" name="icon">
        <IconSelect v-model:value="formState.icon" placeholder="请选择图标" />
      </a-form-item>
      <a-form-item label="重定向地址" name="redirect">
        <a-input v-model:value="formState.redirect" placeholder="请输入重定向地址" allow-clear />
      </a-form-item>
      <a-form-item label="描述" name="describe">
        <a-input v-model:value="formState.describe" placeholder="请输入菜单描述" allow-clear />
      </a-form-item>
      <a-form-item label="是否隐藏菜单" name="isHideInMenu">
        <a-switch v-model:checked="formState.isHideInMenu" checked-children="隐藏" un-checked-children="显示" />
      </a-form-item>
      <a-form-item label="是否隐藏子菜单" name="isHideChildrenInMenu">
        <a-switch v-model:checked="formState.isHideChildrenInMenu" checked-children="隐藏" un-checked-children="显示" />
      </a-form-item>
      <a-form-item label="是否启用" name="isEnabled">
        <a-switch v-model:checked="formState.isEnabled" checked-children="启用" un-checked-children="禁用" />
      </a-form-item>
    </a-form>
  </a-modal>
</template>

<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue';
import { message } from 'ant-design-vue';
import { addAdminMenu, editAdminMenu, getAdminMenuInfo } from '@/api/admin/menu';
import { AdminMenuKey, AdminRouterPath } from '@/api/pattern';
import { DefaultModalWidth } from '@/api/config';
import IconSelect from '@/components/IconSelect.vue';
import type { MenuTreeItem, ReqAdminMenuAdd } from '@/types/admin_menu';
import type { FormInstance } from 'ant-design-vue';

const props = defineProps<{
  open: boolean;
  tree: MenuTreeItem[];
  detailData?: MenuTreeItem;
}>();
const emit = defineEmits<{ (e: 'update:open', value: boolean): void; (e: 'notice'): void }>();

const formRef = ref<FormInstance>();
const confirmLoading = ref(false);

const formState = reactive<{
  parentId?: number;
  name: string;
  path: string;
  key: string;
  sort?: number;
  icon?: string;
  redirect?: string;
  describe?: string;
  isHideInMenu: boolean;
  isHideChildrenInMenu: boolean;
  isEnabled: boolean;
}>({
  parentId: undefined,
  name: '',
  path: '',
  key: '',
  sort: 0,
  icon: '',
  redirect: '/',
  describe: '',
  isHideInMenu: false,
  isHideChildrenInMenu: false,
  isEnabled: true,
});

const rules = {
  name: [
    { required: true, message: '请输入菜单名称' },
    { max: 50, message: '菜单名称长度不能超过50个字符' },
  ],
  path: [
    { required: true, message: '请输入菜单路径' },
    { pattern: AdminRouterPath, message: '路径格式不正确' },
  ],
  key: [
    { required: true, pattern: AdminMenuKey, message: '请按照驼峰法命名' },
  ],
};

/** 把路径转为键名 */
function path2UpperCamelCase(path: string) {
  return path
    ?.split('/')
    .filter((name) => name.length > 0)
    .map((name) => name[0].toUpperCase() + name.substring(1))
    .join('');
}

/** 构建树选择数据：首项为虚拟顶级菜单（parentId=0，与系统设置平级） */
const treeSelectData = computed(() => {
  const build = (list: MenuTreeItem[]): any[] =>
    list.map((item) => ({
      key: item.id,
      value: item.id,
      title: item.name,
      children: item.children?.length ? build(item.children) : undefined,
    }));
  return [{ key: 0, value: 0, title: '顶级菜单' }, ...build(props.tree)];
});

function onPathChange() {
  formState.key = path2UpperCamelCase(formState.path);
}

watch(
  () => props.open,
  async (val) => {
    if (val) {
      if (props.detailData?.id) {
        // 编辑：实时拉取详情回填，避免编辑列表中的过期数据
        const res = await getAdminMenuInfo({ menuId: props.detailData.id });
        const info = res.data as MenuTreeItem;
        formState.parentId = info.parentId || 0;
        formState.name = info.name || '';
        formState.path = info.path || '';
        formState.key = info.key || '';
        formState.sort = info.sort ?? 0;
        formState.icon = info.icon || '';
        formState.redirect = info.redirect || '/';
        formState.describe = info.describe || '';
        formState.isHideInMenu = !!info.hideInMenu;
        formState.isHideChildrenInMenu = !!info.hideChildrenInMenu;
        formState.isEnabled = !!info.enabled;
      } else {
        // 新增：父级取传入的父菜单ID，未指定时默认挂在顶级菜单下
        formRef.value?.resetFields();
        formState.parentId = props.detailData?.parentId ?? 0;
        formState.isEnabled = true;
        formState.isHideInMenu = false;
        formState.isHideChildrenInMenu = false;
        formState.redirect = '/';
      }
    }
  },
);

function handleOk() {
  formRef.value
    ?.validate()
    .then(() => {
      const data: ReqAdminMenuAdd & { id?: number } = {
        ...formState,
        parentId: formState.parentId ?? 0,
      };
      if (props.detailData?.id) {
        // 编辑
        data.id = props.detailData.id;
        confirmLoading.value = true;
        editAdminMenu(data)
          .then((res) => {
            message.success(res.msg, 2);
            emit('notice');
            emit('update:open', false);
          })
          .finally(() => {
            confirmLoading.value = false;
          });
      } else {
        confirmLoading.value = true;
        addAdminMenu(data)
          .then((res) => {
            message.success(res.msg, 2);
            emit('notice');
            emit('update:open', false);
          })
          .finally(() => {
            confirmLoading.value = false;
          });
      }
    })
    .catch(() => {});
}

function handleCancel() {
  emit('update:open', false);
}
</script>
