// admin-vue3x/src/components/PageContainer.vue
<template>
  <div class="page-container">
    <div class="page-header">
      <div class="header-search">
        <slot name="searchArea" />
      </div>
      <div class="header-extra">
        <slot name="extra" />
      </div>
    </div>
    <div class="page-content">
      <slot />
    </div>
    <div v-if="pageInfo" class="page-footer">
      <div class="footer-pageinfo">
        <PageInfo :page-info="pageInfo" />
      </div>
      <div class="footer-pagination">
        <a-pagination
          v-model:current="pageInfo.pageNum"
          v-model:page-size="pageInfo.pageSize"
          :total="pageInfo.total"
          :show-size-changer="true"
          :show-quick-jumper="true"
          :page-size-options="pageSizeOptions"
          show-less-items
          @change="onPageChange"
          @showSizeChange="onSizeChange"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { PageInfoType } from '@/api/types';
import PageInfo from './PageInfo.vue';

const props = defineProps<{
  pageInfo?: PageInfoType;
  pageSizeOptions?: string[];
}>();

const emit = defineEmits<{
  (e: 'pageChange', pageNum: number): void;
  (e: 'pageSizeChange', pageSize: number): void;
}>();

const pageSizeOptions = computed(() => props.pageSizeOptions || ['10', '20', '50', '100']);

const onPageChange = (pageNum: number) => {
  emit('pageChange', pageNum);
};

const onSizeChange = (_current: number, size: number) => {
  emit('pageSizeChange', size);
};
</script>

<style scoped lang="less">
.page-container {
  padding: 16px;
  background: #fff;
  border-radius: 2px;

  .page-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 16px;

    .header-search {
      flex: 1;
    }
  }

  .page-content {
    margin-bottom: 16px;
  }

  .page-footer {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
}
</style>

// admin-react/src/components/PageContainer.tsx
import type { ReactNode } from 'react';
import { Pagination } from 'antd';
import type { PageInfoType } from '@/api/types';
import PageInfo from './PageInfo';

interface PageContainerProps {
  pageInfo?: PageInfoType;
  pageSizeOptions?: string[];
  searchArea?: ReactNode;
  extra?: ReactNode;
  children?: ReactNode;
  onPageChange?: (pageNum: number) => void;
  onPageSizeChange?: (pageSize: number) => void;
}

/** 页面容器：搜索区 + 操作区 + 内容 + 分页 */
export default function PageContainer({
  pageInfo,
  pageSizeOptions,
  searchArea,
  extra,
  children,
  onPageChange,
  onPageSizeChange,
}: PageContainerProps) {
  return (
    <div className="page-container">
      <div className="page-header">
        <div className="header-search">{searchArea}</div>
        <div className="header-extra">{extra}</div>
      </div>
      <div className="page-content">{children}</div>
      {pageInfo && (
        <div className="page-footer">
          <div className="footer-pageinfo">
            <PageInfo pageInfo={pageInfo} />
          </div>
          <div className="footer-pagination">
            <Pagination
              current={pageInfo.pageNum}
              pageSize={pageInfo.pageSize}
              total={pageInfo.total}
              showSizeChanger
              showQuickJumper
              showLessItems
              pageSizeOptions={pageSizeOptions || ['10', '20', '50', '100']}
              onChange={(pageNum, pageSize) => {
                // 页大小变化时 antd 会同时触发 onChange，交由父级按需处理
                if (pageSize !== pageInfo.pageSize) {
                  onPageSizeChange?.(pageSize);
                  return;
                }
                onPageChange?.(pageNum);
              }}
            />
          </div>
        </div>
      )}
    </div>
  );
}
