// admin-vue3x/src/views/account/index.vue
<template>
  <div class="account-page">
    <a-card>
      <a-tabs v-model:active-key="activeKey">
        <a-tab-pane key="account" tab="个人中心">
          <CurrentAccount />
        </a-tab-pane>
        <a-tab-pane key="password" tab="修改密码">
          <CurrentPassword />
        </a-tab-pane>
      </a-tabs>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import CurrentAccount from './components/CurrentAccount.vue';
import CurrentPassword from './components/CurrentPassword.vue';

const activeKey = ref('account');
</script>

<style scoped lang="less">
.account-page {
  max-width: 800px;
}
</style>

// admin-react/src/views/account/index.tsx
import { useState } from 'react';
import { Card, Tabs } from 'antd';
import CurrentAccount from './components/CurrentAccount';
import CurrentPassword from './components/CurrentPassword';

/** 个人中心 */
export default function Account() {
  const [activeKey, setActiveKey] = useState('account');
  return (
    <div style={{ maxWidth: 800 }}>
      <Card>
        <Tabs activeKey={activeKey} onChange={setActiveKey}>
          <Tabs.TabPane key="account" tab="个人中心">
            <CurrentAccount />
          </Tabs.TabPane>
          <Tabs.TabPane key="password" tab="修改密码">
            <CurrentPassword />
          </Tabs.TabPane>
        </Tabs>
      </Card>
    </div>
  );
}
