// admin-react/src/views/admin/role/index.tsx
import { useEffect, useState } from 'react';
import { Button, Form, Input, Popconfirm, Select, Space, Table, Tag, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import {
  DeleteOutlined,
  EditOutlined,
  EyeOutlined,
  PlusOutlined,
  ReloadOutlined,
  SafetyCertificateOutlined,
  SearchOutlined,
} from '@ant-design/icons';
import PageContainer from '@/components/PageContainer';
import Authorization from '@/components/Authorization';
import RowEnabledButton from '@/components/RowEnabledButton';
import AddRoleModal from './components/AddRoleModal';
import EditRoleModal from './components/EditRoleModal';
import DetailRoleDrawer from './components/DetailRoleDrawer';
import BindPermissionsModal from './components/BindPermissionsModal';
import { deleteAdminRole, enableAdminRole, getAdminRoleList } from '@/api/admin/role';
import type { RoleItem } from '@/types/admin_role';
import { DEFAULT_PAGE_INFO } from '@/api/config';
import type { PageInfoType } from '@/api/types';

/** 角色管理 */
export default function AdminRole() {
  const [loading, setLoading] = useState(false);
  const [rows, setRows] = useState<RoleItem[]>([]);
  const [pageInfo, setPageInfo] = useState<PageInfoType>({ ...DEFAULT_PAGE_INFO });
  const [searchForm] = Form.useForm<{ name?: string; enabled?: number }>();
  const [addOpen, setAddOpen] = useState(false);
  const [editOpen, setEditOpen] = useState(false);
  const [detailOpen, setDetailOpen] = useState(false);
  const [bindOpen, setBindOpen] = useState(false);
  const [editData, setEditData] = useState<RoleItem>();
  const [detailData, setDetailData] = useState<RoleItem>();

  const getRows = (page = pageInfo, search = searchForm.getFieldsValue()) => {
    setLoading(true);
    getAdminRoleList({
      pageNum: page.pageNum,
      pageSize: page.pageSize,
      name: search.name,
      enabled: search.enabled ?? 0,
    })
      .then((res) => {
        setRows(res.data.list || []);
        setPageInfo((prev) => ({ ...prev, total: res.data.pageInfo?.total || 0 }));
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    getRows();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const onSearch = () => {
    const next = { ...pageInfo, pageNum: 1 };
    setPageInfo(next);
    getRows(next);
  };

  const onReset = () => {
    searchForm.setFieldsValue({ name: undefined, enabled: 0 });
    onSearch();
  };

  const onPageChange = (pageNum: number) => {
    const next = { ...pageInfo, pageNum };
    setPageInfo(next);
    getRows(next);
  };

  const onPageSizeChange = (pageSize: number) => {
    const next = { ...pageInfo, pageSize, pageNum: 1 };
    setPageInfo(next);
    getRows(next);
  };

  const updateEnabled = (record: RoleItem) => {
    enableAdminRole({ id: record.id, enabled: !record.isEnabled }).then((res) => {
      message.success(res.msg, 2);
      getRows();
    });
  };

  const onDelete = (record: RoleItem) => {
    deleteAdminRole({ id: record.id }).then((res) => {
      message.success(res.msg, 2);
      getRows();
    });
  };

  const columns: ColumnsType<RoleItem> = [
    { title: 'ID', dataIndex: 'id', key: 'id', fixed: 'left', width: 80 },
    {
      title: '角色名称',
      dataIndex: 'name',
      key: 'name',
      width: 160,
      render: (_v, record) => (
        <Space>
          <span>{record.name}</span>
          {record.isSuperAdmin && <Tag color="gold">超级管理员</Tag>}
        </Space>
      ),
    },
    { title: '描述', dataIndex: 'describe', key: 'describe', width: 180 },
    { title: '创建人', dataIndex: 'createAdminName', key: 'createAdminName', width: 120 },
    {
      title: '状态',
      dataIndex: 'isEnabled',
      key: 'isEnabled',
      width: 100,
      render: (_v, record) => (
        <Authorization permission="AdminRoleEdit">
          <Popconfirm
            title={`确定要${record.isEnabled ? '禁用' : '启用'}该角色吗？`}
            okText="确定"
            cancelText="取消"
            onConfirm={() => updateEnabled(record)}
          >
            <RowEnabledButton isEnabled={record.isEnabled} />
          </Popconfirm>
        </Authorization>
      ),
    },
    { title: '创建时间', dataIndex: 'createdAt', key: 'createdAt', width: 180 },
    { title: '更新时间', dataIndex: 'updatedAt', key: 'updatedAt', width: 180 },
    {
      title: '操作',
      dataIndex: 'action',
      key: 'action',
      fixed: 'right',
      width: 320,
      render: (_v, record) => (
        <Space>
          <Authorization permission="AdminRoleView">
            <Button type="link" size="small" icon={<EyeOutlined />} onClick={() => { setDetailData(record); setDetailOpen(true); }}>
              详情
            </Button>
          </Authorization>
          <Authorization permission="AdminRoleEdit">
            {/* 超管角色允许编辑，但仅可修改描述 */}
            <Button type="link" size="small" icon={<EditOutlined />} onClick={() => { setEditData(record); setEditOpen(true); }}>
              编辑
            </Button>
          </Authorization>
          <Authorization permission="AdminRoleBindPermissions">
            {/* 超级管理员角色不允许绑定权限 */}
            {record.id !== 1 && (
              <Button type="link" size="small" icon={<SafetyCertificateOutlined />} onClick={() => { setDetailData(record); setBindOpen(true); }}>
                绑定权限
              </Button>
            )}
          </Authorization>
          <Authorization permission="AdminRoleDelete">
            {!record.isEnabled && (
              <Popconfirm title="确定要删除该角色吗？" okText="确定" cancelText="取消" onConfirm={() => onDelete(record)}>
                <Button type="link" size="small" danger icon={<DeleteOutlined />}>
                  删除
                </Button>
              </Popconfirm>
            )}
          </Authorization>
        </Space>
      ),
    },
  ];

  return (
    <PageContainer
      pageInfo={pageInfo}
      onPageChange={onPageChange}
      onPageSizeChange={onPageSizeChange}
      searchArea={
        <Form layout="inline" form={searchForm} onFinish={onSearch}>
          <Form.Item label="角色名称" name="name">
            <Input placeholder="请输入角色名称" allowClear />
          </Form.Item>
          <Form.Item label="状态" name="enabled" initialValue={0}>
            <Select style={{ width: 120 }} options={[{ value: 0, label: '全部' }, { value: 1, label: '启用' }, { value: 2, label: '禁用' }]} />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button type="primary" htmlType="submit" icon={<SearchOutlined />}>查询</Button>
              <Button icon={<ReloadOutlined />} onClick={onReset}>重置</Button>
            </Space>
          </Form.Item>
        </Form>
      }
      extra={
        <Authorization permission="AdminRoleAdd">
          <Button type="primary" icon={<PlusOutlined />} onClick={() => setAddOpen(true)}>新建角色</Button>
        </Authorization>
      }
    >
      <Table columns={columns} dataSource={rows} loading={loading} pagination={false} rowKey="id" scroll={{ x: 1320 }} />
      <AddRoleModal open={addOpen} onClose={() => setAddOpen(false)} onNotice={onModalNotice} />
      <EditRoleModal open={editOpen} detailData={editData} onClose={() => setEditOpen(false)} onNotice={onModalNotice} />
      <DetailRoleDrawer open={detailOpen} detailData={detailData} onClose={() => setDetailOpen(false)} />
      <BindPermissionsModal open={bindOpen} detailData={detailData} onClose={() => setBindOpen(false)} onNotice={onModalNotice} />
    </PageContainer>
  );

  function onModalNotice() {
    getRows();
  }
}

// admin-vue3x/src/views/admin/role/index.vue
<template>
  <PageContainer :page-info="pageInfo" @page-change="onPageChange" @page-size-change="onPageSizeChange">
    <template #searchArea>
      <a-form layout="inline" :model="searchForm" class="search-form" @finish="onSearch">
        <a-form-item label="角色名称" name="name">
          <a-input v-model:value="searchForm.name" placeholder="请输入角色名称" allow-clear />
        </a-form-item>
        <a-form-item label="状态" name="enabled">
          <a-select v-model:value="searchForm.enabled" style="width: 120px" placeholder="全部">
            <a-select-option :value="0">全部</a-select-option>
            <a-select-option :value="1">启用</a-select-option>
            <a-select-option :value="2">禁用</a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item>
          <a-space>
            <a-button type="primary" html-type="submit">
              <template #icon><SearchOutlined /></template>
              查询
            </a-button>
            <a-button @click="onReset">
              <template #icon><ReloadOutlined /></template>
              重置
            </a-button>
          </a-space>
        </a-form-item>
      </a-form>
    </template>
    <template #extra>
      <Authorization permission="AdminRoleAdd">
        <a-button type="primary" @click="openAddModal">
          <template #icon><PlusOutlined /></template>
          新建角色
        </a-button>
      </Authorization>
    </template>

    <a-table
      :columns="columns"
      :data-source="rows"
      :loading="loading"
      :pagination="false"
      row-key="id"
      :scroll="{ x: 1320 }"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'name'">
          <a-space>
            <span>{{ record.name }}</span>
            <a-tag v-if="record.isSuperAdmin" color="gold">超级管理员</a-tag>
          </a-space>
        </template>
        <template v-else-if="column.key === 'isEnabled'">
          <Authorization permission="AdminRoleEdit">
            <a-popconfirm
              :title="`确定要${record.isEnabled ? '禁用' : '启用'}该角色吗？`"
              ok-text="确定"
              cancel-text="取消"
              @confirm="updateEnabled(record)"
            >
              <RowEnabledButton :is-enabled="record.isEnabled" />
            </a-popconfirm>
          </Authorization>
        </template>
        <template v-else-if="column.key === 'action'">
          <a-space>
            <Authorization permission="AdminRoleView">
              <a-button type="link" size="small" @click="openDetailModal(record)">
                <template #icon><EyeOutlined /></template>
                详情
              </a-button>
            </Authorization>
            <Authorization permission="AdminRoleEdit">
              <!-- 超管角色允许编辑，但仅可修改描述 -->
              <a-button type="link" size="small" @click="openEditModal(record)">
                <template #icon><EditOutlined /></template>
                编辑
              </a-button>
            </Authorization>
            <Authorization permission="AdminRoleBindPermissions">
              <!-- 超级管理员角色不允许绑定权限 -->
              <a-button v-if="record.id !== 1" type="link" size="small" @click="openBindModal(record)">
                <template #icon><SafetyCertificateOutlined /></template>
                绑定权限
              </a-button>
            </Authorization>
            <Authorization permission="AdminRoleDelete">
              <a-popconfirm
                v-if="!record.isEnabled"
                title="确定要删除该角色吗？"
                ok-text="确定"
                cancel-text="取消"
                @confirm="onDelete(record)"
              >
                <a-button type="link" size="small" danger>
                  <template #icon><DeleteOutlined /></template>
                  删除
                </a-button>
              </a-popconfirm>
            </Authorization>
          </a-space>
        </template>
      </template>
    </a-table>

    <AddRoleModal v-model:open="addModalStatus" @notice="onModalNotice" />
    <EditRoleModal v-model:open="editModalStatus" :detail-data="editData" @notice="onModalNotice" />
    <DetailRoleDrawer v-model:open="detailModalStatus" :detail-data="detailData" />
    <BindPermissionsModal
      v-model:open="bindModalStatus"
      :detail-data="detailData"
      @notice="onModalNotice"
    />
  </PageContainer>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { message } from 'ant-design-vue';
import {
  SearchOutlined,
  ReloadOutlined,
  PlusOutlined,
  EyeOutlined,
  EditOutlined,
  SafetyCertificateOutlined,
  DeleteOutlined,
} from '@ant-design/icons-vue';
import PageContainer from '@/components/PageContainer.vue';
import Authorization from '@/components/Authorization.vue';
import RowEnabledButton from '@/components/RowEnabledButton.vue';
import AddRoleModal from './components/AddRoleModal.vue';
import EditRoleModal from './components/EditRoleModal.vue';
import DetailRoleDrawer from './components/DetailRoleDrawer.vue';
import BindPermissionsModal from './components/BindPermissionsModal.vue';
import { getAdminRoleList, deleteAdminRole, enableAdminRole } from '@/api/admin/role';
import type { RoleItem } from '@/types/admin_role';
import { DEFAULT_PAGE_INFO } from '@/api/config';
import type { PageInfoType } from '@/api/types';

const loading = ref(false);
const rows = ref<RoleItem[]>([]);
const pageInfo = reactive<PageInfoType>({ ...DEFAULT_PAGE_INFO });

const searchForm = reactive<{ name?: string; enabled?: number }>({
  name: undefined,
  enabled: 0,
});

const addModalStatus = ref(false);
const editModalStatus = ref(false);
const detailModalStatus = ref(false);
const bindModalStatus = ref(false);
const editData = ref<RoleItem>();
const detailData = ref<RoleItem>();

const columns = [
  { title: 'ID', dataIndex: 'id', key: 'id', fixed: 'left', width: 80 },
  { title: '角色名称', dataIndex: 'name', key: 'name', width: 160 },
  { title: '描述', dataIndex: 'describe', key: 'describe', width: 180 },
  { title: '创建人', dataIndex: 'createAdminName', key: 'createAdminName', width: 120 },
  { title: '状态', dataIndex: 'isEnabled', key: 'isEnabled', width: 100 },
  { title: '创建时间', dataIndex: 'createdAt', key: 'createdAt', width: 180 },
  { title: '更新时间', dataIndex: 'updatedAt', key: 'updatedAt', width: 180 },
  { title: '操作', dataIndex: 'action', key: 'action', fixed: 'right', width: 320 },
];

function getRows() {
  loading.value = true;
  getAdminRoleList({
    pageNum: pageInfo.pageNum,
    pageSize: pageInfo.pageSize,
    name: searchForm.name,
    enabled: searchForm.enabled,
  })
    .then((res) => {
      rows.value = res.data.list || [];
      pageInfo.total = res.data.pageInfo?.total || 0;
    })
    .finally(() => {
      loading.value = false;
    });
}

function onSearch() {
  if (pageInfo.pageNum !== 1) {
    pageInfo.pageNum = 1;
    getRows();
  } else {
    getRows();
  }
}

function onReset() {
  searchForm.name = undefined;
  searchForm.enabled = 0;
  onSearch();
}

function onPageChange(pageNum: number) {
  pageInfo.pageNum = pageNum;
  getRows();
}

function onPageSizeChange(pageSize: number) {
  pageInfo.pageSize = pageSize;
  pageInfo.pageNum = 1;
  getRows();
}

function updateEnabled(record: RoleItem) {
  enableAdminRole({ id: record.id, enabled: !record.isEnabled }).then((res) => {
    message.success(res.msg, 2);
    getRows();
  });
}

function onDelete(record: RoleItem) {
  deleteAdminRole({ id: record.id }).then((res) => {
    message.success(res.msg, 2);
    getRows();
  });
}

function openAddModal() {
  addModalStatus.value = true;
}

function openEditModal(record: RoleItem) {
  editData.value = record;
  editModalStatus.value = true;
}

function openDetailModal(record: RoleItem) {
  detailData.value = record;
  detailModalStatus.value = true;
}

function openBindModal(record: RoleItem) {
  detailData.value = record;
  bindModalStatus.value = true;
}

function onModalNotice() {
  getRows();
}

onMounted(() => {
  getRows();
});
</script>

<style scoped lang="less">
.search-form {
  .ant-form-item {
    margin-bottom: 8px;
  }
}
</style>
