// admin-vue3x/src/views/admin/menu/index.vue
<template>
  <PageContainer title="菜单管理">
    <template #extra>
      <a-button type="primary" @click="openAddModal()">
        <template #icon><PlusOutlined /></template>
        新建菜单
      </a-button>
    </template>

    <a-table
      :columns="columns"
      :data-source="rows"
      :loading="loading"
      :pagination="false"
      :default-expand-all-rows="true"
      row-key="id"
      :scroll="{ x: 1100 }"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'name'">
          <a-space>
            <span>{{ record.name }}</span>
          </a-space>
        </template>
        <template v-else-if="column.key === 'isEnabled'">
          <a-popconfirm
            :title="`确定要${record.enabled ? '禁用' : '启用'}该菜单吗？`"
            ok-text="确定"
            cancel-text="取消"
            @confirm="updateEnabled(record)"
          >
            <a-switch :checked="record.enabled" checked-children="启用" un-checked-children="禁用" />
          </a-popconfirm>
        </template>
        <template v-else-if="column.key === 'hideInMenu'">
          <a-switch
            :checked="!record.hideInMenu"
            checked-children="显示"
            un-checked-children="隐藏"
            @change="updateShow(record)"
          />
        </template>
        <template v-else-if="column.key === 'action'">
          <a-space>
            <Authorization permission="AdminMenuEdit">
              <a-button type="link" size="small" @click="openAddModal(record)">新增子菜单</a-button>
            </Authorization>
            <Authorization permission="AdminMenuEdit">
              <a-button type="link" size="small" @click="openEditModal(record)">编辑</a-button>
            </Authorization>
            <Authorization permission="AdminMenuView">
              <a-button type="link" size="small" @click="openDetailModal(record)">详情</a-button>
            </Authorization>
            <Authorization permission="AdminMenuEdit">
              <a-button type="link" size="small" @click="openPermissionsModal(record)">权限配置</a-button>
            </Authorization>
            <Authorization permission="AdminMenuDelete">
              <a-popconfirm
                v-if="!record.enabled"
                title="确定要删除该菜单吗？"
                ok-text="确定"
                cancel-text="取消"
                @confirm="onDelete(record)"
              >
                <a-button type="link" size="small" danger>删除</a-button>
              </a-popconfirm>
            </Authorization>
          </a-space>
        </template>
      </template>
    </a-table>

    <SaveMenuModal
      v-model:open="saveModalStatus"
      :tree="rows"
      :detail-data="saveData"
      @notice="onModalNotice"
    />
    <DetailMenuDrawer v-model:open="detailModalStatus" :detail-data="detailData" />
    <PermissionsSaveModal v-model:open="permissionsModalStatus" :detail-data="detailData" />
  </PageContainer>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { message } from 'ant-design-vue';
import { PlusOutlined } from '@ant-design/icons-vue';
import PageContainer from '@/components/PageContainer.vue';
import Authorization from '@/components/Authorization.vue';
import SaveMenuModal from './components/SaveMenuModal.vue';
import DetailMenuDrawer from './components/DetailMenuDrawer.vue';
import PermissionsSaveModal from './components/PermissionsSaveModal.vue';
import { getAdminMenuTree, deleteAdminMenu, enableAdminMenu, showAdminMenu } from '@/api/admin/menu';
import type { MenuTreeItem } from '@/types/admin_menu';

const loading = ref(false);
const rows = ref<MenuTreeItem[]>([]);

const saveModalStatus = ref(false);
const detailModalStatus = ref(false);
const permissionsModalStatus = ref(false);
const saveData = ref<MenuTreeItem>();
const detailData = ref<MenuTreeItem>();

const columns = [
  { title: '菜单名称', dataIndex: 'name', key: 'name', width: 220 },
  { title: '键名', dataIndex: 'key', key: 'key', width: 160 },
  { title: '菜单路径', dataIndex: 'path', key: 'path', width: 180 },
  { title: '排序', dataIndex: 'sort', key: 'sort', width: 80 },
  { title: '状态', dataIndex: 'enabled', key: 'isEnabled', width: 100 },
  { title: '是否显示', dataIndex: 'hideInMenu', key: 'hideInMenu', width: 100 },
  { title: '创建时间', dataIndex: 'createTime', key: 'createTime', width: 180, customRender: ({ text }: { text: number }) => formatTime(text) },
  { title: '操作', dataIndex: 'action', key: 'action', fixed: 'right', width: 320 },
];

function formatTime(time?: number) {
  if (!time) return '';
  const d = new Date(time * 1000);
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

function getRows() {
  loading.value = true;
  getAdminMenuTree()
    .then((res) => {
      rows.value = res.data.list || [];
    })
    .finally(() => {
      loading.value = false;
    });
}

function updateEnabled(record: MenuTreeItem) {
  enableAdminMenu({ menuId: record.id, enabled: !record.enabled }).then((res) => {
    message.success(res.msg, 2);
    getRows();
  });
}

function updateShow(record: MenuTreeItem) {
  showAdminMenu({ menuId: record.id, show: !!record.hideInMenu }).then((res) => {
    message.success(res.msg, 2);
    getRows();
  });
}

function onDelete(record: MenuTreeItem) {
  deleteAdminMenu({ menuId: record.id }).then((res) => {
    message.success(res.msg, 2);
    getRows();
  });
}

function openAddModal(parent?: MenuTreeItem) {
  saveData.value = parent ? { ...parent } : undefined;
  saveModalStatus.value = true;
}

function openEditModal(record: MenuTreeItem) {
  saveData.value = { ...record };
  saveModalStatus.value = true;
}

function openDetailModal(record: MenuTreeItem) {
  detailData.value = record;
  detailModalStatus.value = true;
}

function openPermissionsModal(record: MenuTreeItem) {
  detailData.value = record;
  permissionsModalStatus.value = true;
}

function onModalNotice() {
  getRows();
}

onMounted(() => {
  getRows();
});
</script>

// admin-frontend/src/pages/Admin/Menu/index.tsx
import React, { useEffect, useState } from 'react';
import { Container, Content } from '@/components/PageContainer';
import { Form, Button, Space, Table, message, Popconfirm, Switch } from 'antd';
import { PlusOutlined } from '@ant-design/icons';
import { ResponseBodyType } from '@/services/apis/types';
import {
  adminMenuDelete,
  adminMenuDetail,
  adminMenuEnable,
  adminMenuPermissions,
  adminMenuShow,
  adminMenuTree,
} from '@/services/apis/admin/menu';
import { ColumnsType } from 'antd/lib/table';
import Authorization from '@/components/Autuorization';
import AdminMenuDetailModal, { NoticeModalPropsType } from './detail';
import AdminMenuSaveModal from './edit';
import SavePermissionsModal from './components/PermissionsSave';
import FetchButton from '@/components/FetchButton';
import { RowEnabledButton } from '@/components';
import { MenuTreeItem, ReqAdminMenuShow } from '@/proto/admin_ts/admin_menu';
import { AdminMenuModel } from '@/proto/admin_ts/admin_model';

const Admin: React.FC = () => {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState<boolean>(false);
  const [detailData, setDetailData] = useState<AdminMenuModel>();
  const [rowsData, setRowsData] = useState<MenuTreeItem[]>([]);
  const [detailModalStatus, setDetailModalStatus] = useState<boolean>(false);
  const [saveModalStatus, setSaveModalStatus] = useState<boolean>(false);
  const [savePermissionsModalStatus, setSaveMenuPermissionsModalStatus] = useState<boolean>(false);
  const [menuPermissionsDetail, setMenuPermissionsDetail] = useState();


  // 获取菜单列表
  function getRows(data?: object) {
    console.log('data:', data)
    setLoading(true);
    adminMenuTree()
      .then((res: ResponseBodyType) => {
        const resData: MenuTreeItem[] = res.data;
        setRowsData(resData);
      })
      .catch((err) => {
        console.log('error', err);
      })
      .finally(() => {
        setLoading(false);
      });
  }

  function tableChange() {
    getRows();
  }

  // 菜单状态更新
  function updateMenuStatus(record: MenuTreeItem, field: string) {
    const updateData: ReqAdminMenuShow = {
      menuId: record.id,
      field: field,
      show: !record[field]
    };

    adminMenuShow(updateData).then((res) => {
      message.success(res.msg, MessageDuritain, () => {
        getRows();
      });
    });
  }

  function updateMenuEnabled(record: MenuTreeItem) {
    adminMenuEnable({
      menuId: record.id,
      enabled: !record.enabled,
    }).then((res) => {
      message.success(res.msg, MessageDuritain, () => {
        getRows();
      });
    });
  }

  // 菜单详情
  function openDetailModal(record: MenuTreeItem) {
    adminMenuDetail({ menuId: record.id }).then((res) => {
      setDetailData(res.data.data);
      setDetailModalStatus(true);
    });
  }

  // 菜单编辑
  function openEditModal(record: MenuTreeItem) {
    adminMenuDetail({ menuId: record.id }).then((res) => {
      setDetailData(res.data.data)
      setSaveModalStatus(true)
    });
  }

  // 菜单添加
  function openAddModal(record: MenuTreeItem) {
    setDetailData({
      parentId: record?.id ?? 0
    })
    setSaveModalStatus(true)
  }

  /**
   * 保存菜单权限
   * @param record
   */
  function openSavePermissionsModal(record: MenuTreeItem) {
    adminMenuPermissions({ menuId: record.id }).then((res) => {
      setMenuPermissionsDetail(res.data || { menuId: record.id });
      setSaveMenuPermissionsModalStatus(true);
    });
  }

  function noticeDetailModal(data: NoticeModalPropsType) {
    setDetailData({});
    setDetailModalStatus(false);
    if (data.reload) {
      getRows();
    }
  }

  function noticeSaveModal(data: NoticeSaveModalPropsType) {
    setDetailData({});
    setSaveModalStatus(false);
    if (data.reload) {
      getRows();
    }
  }

  function noticeAddPermissionModal(data: NoticeModalPropsType) {
    setDetailData({});
    setMenuPermissionsDetail(undefined);
    setSaveMenuPermissionsModalStatus(false);
    if (data.reload) {
      getRows({ ...form.getFieldsValue() });
    }
  }

  // 删除菜单
  function onDelete(record: MenuTreeItem) {
    adminMenuDelete({ menuId: record.id }).then((res) => {
      message.success(res.msg, MessageDuritain);
      getRows({ ...form.getFieldsValue() });
    });
  }

  useEffect(() => {
    getRows();
  }, []);


  const showTrueText = '隐藏'
  const showFalseText = '显示'

  const columns: ColumnsType<any> = [
    {
      title: '名称',
      align: 'left',
      dataIndex: 'name',
    },
    {
      title: '路由',
      align: 'left',
      dataIndex: 'path',
    },
    {
      title: '菜单',
      align: 'left',
      dataIndex: 'hideInMenu',
      render(hideInMenu: boolean, record: MenuTreeItem) {
        if (record.path === '/') {
          return <></>;
        }
        return (
          <Authorization
            name="AdminUserEdit"
            forbidden={
              <RowEnabledButton danger={!!hideInMenu} isEnabled={hideInMenu} trueText={showTrueText} falseText={showFalseText} />
            }
          >
            <Popconfirm
              title={`确定在菜单中${record.hideInMenu ? '隐藏' : '显示'}该项吗？`}
              okText="确定"
              cancelText="取消"
              onConfirm={() => updateMenuStatus(record, 'hideInMenu')}
            >
              <RowEnabledButton danger={!!hideInMenu} isEnabled={hideInMenu} trueText={showTrueText} falseText={showFalseText} />
            </Popconfirm>
          </Authorization>
        );
      },
    },
    {
      title: '子菜单',
      align: 'left',
      dataIndex: 'hideChildrenInMenu',
      render(hideChildrenInMenu: boolean, record: MenuTreeItem) {
        if (record.path === '/') {
          return <></>;
        }
        return (
          <Authorization
            name="AdminUserEdit"
            forbidden={
              <RowEnabledButton danger={!!hideChildrenInMenu} isEnabled={hideChildrenInMenu} trueText={showTrueText} falseText={showFalseText} />
            }
          >
            <Popconfirm
              title={`确定在菜单中${record.hideChildrenInMenu ? '隐藏' : '显示'}该项吗？`}
              okText="确定"
              cancelText="取消"
              onConfirm={() => updateMenuStatus(record, 'hideChildrenInMenu')}
            >
              <RowEnabledButton danger={!!hideChildrenInMenu} isEnabled={hideChildrenInMenu} trueText={showTrueText} falseText={showFalseText} />
            </Popconfirm>
          </Authorization>
        );
      },
    },
    {
      title: '状态',
      width: '6rem',
      align: 'center',
      dataIndex: 'enabled',
      render(enabled: boolean, record: MenuTreeItem) {
        if (record.path === '/') {
          return <></>;
        }
        return (
          <Authorization
            name="AdminUserEdit"
            forbidden={
              <RowEnabledButton isEnabled={enabled} />
            }
          >
            <Popconfirm
              title={`确定${record.enabled ? '禁用' : '启用'}该项吗？`}
              okText="确定"
              cancelText="取消"
              onConfirm={() => updateMenuEnabled(record)}
            >
              <RowEnabledButton isEnabled={enabled} />
            </Popconfirm>
          </Authorization>
        );
      },
    },
    {
      title: '操作',
      align: 'left',
      width: '10rem',
      render(text, record: MenuTreeItem) {
        if (record.path === '/') {
          return <></>;
        }
        return (
          <Space>
            <Authorization name="AdminMenuView">
              <FetchButton onClick={() => openDetailModal(record)}>详情</FetchButton>
            </Authorization>
            <Authorization name="AdminMenuEdit">
              <FetchButton onClick={() => openAddModal(record)}>添加子菜单</FetchButton>
            </Authorization>
            <Authorization name="AdminMenuEdit">
              {record.hideInMenu ||
                (record.children !== undefined &&
                  record?.children.length > 0 &&
                  !record.hideChildrenInMenu) ? (
                ''
              ) : (
                <FetchButton onClick={() => openSavePermissionsModal(record)}>创建权限</FetchButton>
              )}
            </Authorization>
            <Authorization name="AdminMenuEdit">
              <FetchButton onClick={() => openEditModal(record)}>编辑</FetchButton>
            </Authorization>

            {/* 禁用的才能删除 */}
            <Authorization name="AdminMenuDelete">
              {!record.enabled ? (
                <Popconfirm
                  title="确定要删除该菜单吗？"
                  okText="确定"
                  cancelText="取消"
                  onConfirm={() => onDelete(record)}
                >
                  <FetchButton danger>删除</FetchButton>
                </Popconfirm>
              ) : (
                ''
              )}
            </Authorization>
          </Space>
        );
      },
    },
  ];

  return (
    <Container>
      <Content>
        {/* button */}
        <Space style={{ marginBottom: '1rem' }}>
          <Authorization name="AdminMenuEdit">
            <Button type="primary" onClick={() => openAddModal()}>
              <PlusOutlined />
              新建菜单
            </Button>
          </Authorization>
        </Space>

        {/* table */}
        {rowsData.length ? (
          <Table
            sticky
            key={'id'}
            rowKey="id"
            scroll={{ x: 'auto' }}
            expandable={{
              defaultExpandAllRows: true,
              fixed: 'left',
              indentSize: 24,
            }}
            loading={loading}
            columns={columns}
            pagination={false}
            dataSource={rowsData}
            onChange={tableChange}
          />
        ) : (
          <></>
        )}
      </Content>

      {/* modal */}

      <AdminMenuDetailModal
        modalStatus={detailModalStatus}
        detailData={detailData}
        noticeModal={noticeDetailModal}
      />

      <AdminMenuSaveModal
        modalStatus={saveModalStatus}
        detailData={detailData}
        noticeModal={noticeSaveModal}
      />

      {/* {menuPermissionsDetail && menuPermissionsDetail.menu && menuPermissionsDetail.menu?.id > 0 ? (
        <SavePermissionsModal
          modalStatus={savePermissionsModalStatus}
          detailData={menuPermissionsDetail}
          noticeModal={noticeAddPermissionModal}
        />
      ) : (
        ''
      )} */}
    </Container>
  );
};

export default Admin;
