// admin-vue3x/src/views/admin/role/components/BindPermissionsModal.vue
<template>
  <a-modal
    :open="open"
    title="绑定权限"
    :width="DefaultModalWidth"
    :confirm-loading="confirmLoading"
    :mask-closable="false"
    ok-text="保存"
    cancel-text="取消"
    @ok="handleOk"
    @cancel="emit('update:open', false)"
  >
    <a-spin :spinning="loading">
      <a-alert
        v-if="detailData"
        :message="`角色：${detailData.name}`"
        type="info"
        show-icon
        style="margin-bottom: 12px"
      />
      <a-tree
        v-if="treeData.length > 0"
        ref="treeRef"
        :key="treeKey"
        :tree-data="treeData"
        checkable
        :checked-keys="checkedKeys"
        :default-expanded-keys="expandedKeys"
        @check="onCheck"
      />
    </a-spin>
  </a-modal>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { message } from 'ant-design-vue';
import { getAdminRolePermissions, bindAdminRolePermissions } from '@/api/admin/role';
import { getAdminMenuMode } from '@/api/admin/menu';
import { DefaultModalWidth } from '@/api/config';
import type { RoleItem } from '@/types/admin_role';
import type { MenuModeItem } from '@/types/admin_menu';

const props = defineProps<{
  open: boolean;
  detailData?: RoleItem;
}>();
const emit = defineEmits<{ (e: 'update:open', value: boolean): void; (e: 'notice'): void }>();

const treeRef = ref();
const loading = ref(false);
const confirmLoading = ref(false);
const treeKey = ref(0);
const treeData = ref<any[]>([]);
const checkedKeys = ref<number[]>([]);
const halfCheckedKeys = ref<number[]>([]);
const expandedKeys = ref<(string | number)[]>([]);

/** 默认只展开第一级（模型），第二级页面默认收起，超过 2 级的内容（权限）不显示 */
function collectExpandKeys(nodes: any[]): (string | number)[] {
  return nodes.filter((node) => node.children?.length).map((node) => node.key);
}

function buildTree(modes: MenuModeItem[]) {
  return modes.map((mode) => ({
    key: `model-${mode.modelId}`,
    title: mode.modelName,
    children: (mode.pages || []).map((page) => ({
      key: `page-${page.pageId}`,
      title: page.pageName,
      children: (page.permissions || []).map((perm) => ({
        key: perm.permissionId as number,
        title: `${perm.permissionName}（${perm.permissionTypeName}）`,
      })),
    })),
  }));
}

watch(
  () => props.open,
  (val) => {
    if (val && props.detailData) {
      loading.value = true;
      checkedKeys.value = [];
      Promise.all([
        getAdminMenuMode({}),
        getAdminRolePermissions({ id: props.detailData.id }),
      ])
        .then(([modeRes, permRes]) => {
          treeData.value = buildTree(modeRes.data.modes || []);
          treeKey.value += 1;
          expandedKeys.value = collectExpandKeys(treeData.value);
          const rolePerms = permRes.data.list || [];
          checkedKeys.value = rolePerms.map((item) => item.permissionId).filter((id): id is number => !!id);
        })
        .finally(() => {
          loading.value = false;
        });
    }
  },
);

function onCheck(keys: (string | number)[], info: { halfCheckedKeys: (string | number)[] }) {
  checkedKeys.value = keys.filter((k) => typeof k === 'number') as number[];
  halfCheckedKeys.value = info.halfCheckedKeys.filter((k) => typeof k === 'number') as number[];
}

function handleOk() {
  confirmLoading.value = true;
  bindAdminRolePermissions({
    id: props.detailData?.id,
    permissionIds: [...checkedKeys.value, ...halfCheckedKeys.value],
  })
    .then((res) => {
      message.success(res.msg, 2);
      emit('notice');
      emit('update:open', false);
    })
    .finally(() => {
      confirmLoading.value = false;
    });
}
</script>

// admin-react/src/views/admin/role/components/BindPermissionsModal.tsx
import { useEffect, useState } from 'react';
import { Alert, Modal, Spin, Tree, message } from 'antd';
import { getAdminRolePermissions, bindAdminRolePermissions } from '@/api/admin/role';
import { getAdminMenuMode } from '@/api/admin/menu';
import { DefaultModalWidth } from '@/api/config';
import type { RoleItem } from '@/types/admin_role';
import type { MenuModeItem } from '@/types/admin_menu';

interface BindPermissionsModalProps {
  open: boolean;
  detailData?: RoleItem;
  onClose: () => void;
  onNotice: () => void;
}

interface TreeNode {
  key: string | number;
  title: string;
  children?: TreeNode[];
}

/** 默认只展开第一级（模型），第二级页面默认收起 */
function collectExpandKeys(nodes: TreeNode[]): (string | number)[] {
  return nodes.filter((node) => node.children?.length).map((node) => node.key);
}

/** 构建 模型→页面→权限 全量树 */
function buildTree(modes: MenuModeItem[]): TreeNode[] {
  return modes.map((mode) => ({
    key: `model-${mode.modelId}`,
    title: mode.modelName ?? '',
    children: (mode.pages || []).map((page) => ({
      key: `page-${page.pageId}`,
      title: page.pageName ?? '',
      children: (page.permissions || []).map((perm) => ({
        key: perm.permissionId as number,
        title: `${perm.permissionName}（${perm.permissionTypeName}）`,
      })),
    })),
  }));
}

/** 角色绑定权限 */
export default function BindPermissionsModal({ open, detailData, onClose, onNotice }: BindPermissionsModalProps) {
  const [loading, setLoading] = useState(false);
  const [confirmLoading, setConfirmLoading] = useState(false);
  const [treeData, setTreeData] = useState<TreeNode[]>([]);
  const [checkedKeys, setCheckedKeys] = useState<number[]>([]);
  const [halfCheckedKeys, setHalfCheckedKeys] = useState<number[]>([]);
  const [expandedKeys, setExpandedKeys] = useState<(string | number)[]>([]);
  const [treeKey, setTreeKey] = useState(0);

  useEffect(() => {
    if (open && detailData) {
      setLoading(true);
      setCheckedKeys([]);
      Promise.all([getAdminMenuMode({}), getAdminRolePermissions({ id: detailData.id })])
        .then(([modeRes, permRes]) => {
          const tree = buildTree(modeRes.data.modes || []);
          setTreeData(tree);
          setExpandedKeys(collectExpandKeys(tree));
          const rolePerms = permRes.data.list || [];
          setCheckedKeys(rolePerms.map((item) => item.permissionId).filter((id): id is number => !!id));
          setTreeKey((k) => k + 1);
        })
        .finally(() => setLoading(false));
    }
  }, [open, detailData]);

  const onCheck = (checked: { checked: (string | number)[]; halfChecked: (string | number)[] }) => {
    setCheckedKeys(checked.checked.filter((k) => typeof k === 'number') as number[]);
    setHalfCheckedKeys(checked.halfChecked.filter((k) => typeof k === 'number') as number[]);
  };

  const handleOk = () => {
    setConfirmLoading(true);
    bindAdminRolePermissions({
      id: detailData?.id,
      permissionIds: [...checkedKeys, ...halfCheckedKeys],
    })
      .then((res) => {
        message.success(res.msg, 2);
        onNotice();
        onClose();
      })
      .finally(() => setConfirmLoading(false));
  };

  return (
    <Modal open={open} title="绑定权限" width={DefaultModalWidth} confirmLoading={confirmLoading} maskClosable={false} okText="保存" cancelText="取消" onOk={handleOk} onCancel={onClose}>
      <Spin spinning={loading}>
        {detailData && <Alert message={`角色：${detailData.name}`} type="info" showIcon style={{ marginBottom: 12 }} />}
        {treeData.length > 0 && (
          <Tree
            key={treeKey}
            treeData={treeData}
            checkable
            checkedKeys={checkedKeys}
            defaultExpandedKeys={expandedKeys}
            onCheck={onCheck as never}
          />
        )}
      </Spin>
    </Modal>
  );
}
