// admin-frontend/src/pages/Admin/Api/index.tsx
import React, { useEffect, useState } from 'react';
import { Container, Content, Search } from '@/components/PageContainer';
import {
  Form,
  Input,
  Button,
  Select,
  Row,
  Col,
  Space,
  Table,
  message,
  Popconfirm,
  Switch,
  App,
} from 'antd';
import { SearchOutlined, ReloadOutlined, PlusOutlined } from '@ant-design/icons';
import type { Gutter } from 'antd/lib/grid/row';
import {
  adminAPIDelete,
  adminAPIDetail,
  adminAPIEnable,
  adminAPIList,
} from '@/services/apis/admin/resource';
import { DEFAULT_PAGE_INFO } from '@/services/apis/config';
import { ColumnsType } from 'antd/lib/table';
import Authorization from '@/components/Autuorization';
import AdminAPIAddModal, { NoticeModalPropsType } from './add';
import AdminAPIEditModal from './edit';
import AdminAPIDetailModal from './detail';
import FetchButton from '@/components/FetchButton';
import { DefaultPagination } from '@/components/PageContainer/Pagination';
import { ReqAdminApiEnable, ReqAdminApiList, RespAdminApiListData } from '@/proto/admin_ts/admin_api';
import { AdminApiItem } from '@/proto/admin_ts/common';
import { PageInfoType } from '@/services/apis/types';
import { handlePagination, searchResetPageInfo } from '@/services/common/utils';
import { RowEnabledButton } from '@/components';

const FormSearchRowGutter: [Gutter, Gutter] = [12, 0];
const FormSearchRowColSpan = 5.2;

const Admin: React.FC = () => {
  const { message } = App.useApp()
  const [form] = Form.useForm();
  const [loading, setLoading] = useState<boolean>(false);
  const [pageInfo, setPageInfo] = useState<PageInfoType>({ ...DEFAULT_PAGE_INFO });
  const [detailData, setDetailData] = useState<AdminApiItem>();
  const [rowsData, setRowsData] = useState<AdminApiItem[]>([]);
  const [detailModalStatus, setDetailModalStatus] = useState<boolean>(false);
  const [editModalStatus, setEditModalStatus] = useState<boolean>(false);
  const [addModalStatus, setAddModalStatus] = useState<boolean>(false);

  const columns: ColumnsType<any> = [
    {
      title: 'ID',
      dataIndex: 'id',
      width: '6rem',
      align: 'center',
      sorter: true,
    },
    {
      title: '名称',
      align: 'left',
      width: '12rem',
      dataIndex: 'name',
    },
    {
      title: '路由',
      align: 'left',
      dataIndex: 'path',
    },
    {
      title: '唯一键',
      align: 'left',
      dataIndex: 'key',
      sorter: true,
    },
    {
      title: '创建时间',
      align: 'center',
      width: '15rem',
      dataIndex: 'createdAt',
      sorter: true,
    },
    {
      title: '更新时间',
      align: 'center',
      width: '15rem',
      dataIndex: 'updatedAt',
      sorter: true,
    },
    {
      title: '状态',
      width: '6rem',
      align: 'center',
      dataIndex: 'isEnabled',
      render(isEnabled: boolean, record: AdminApiItem) {
        return (
          <Authorization
            name="AdminApiEdit"
            forbidden={
              <RowEnabledButton isEnabled={isEnabled} disabled={false} />
            }
          >
            <Popconfirm
              title={`确定要${record.isEnabled ? '禁用' : '启用'}该账号吗？`}
              okText="确定"
              cancelText="取消"
              onConfirm={() => updateEnabled(record)}
            >
              <RowEnabledButton isEnabled={isEnabled} disabled={false} />
            </Popconfirm>
          </Authorization>
        );
      },
    },
    {
      title: '操作',
      align: 'left',
      width: '10rem',
      fixed: 'right',
      render(text, record: AdminApiItem) {
        return (
          <Space>
            <Authorization name="AdminApiView">
              <FetchButton onClick={() => openDetailModal(record)}>详情</FetchButton>
            </Authorization>
            <Authorization name="AdminApiEdit">
              <FetchButton onClick={() => openEditModal(record)}>编辑</FetchButton>
            </Authorization>

            {/* 禁用的才能删除 */}
            <Authorization name="AdminApiDelete">
              {!record.isEnabled ? (
                <Popconfirm
                  title="确定要删除该接口资源吗？"
                  okText="确定"
                  cancelText="取消"
                  onConfirm={() => onDelete(record)}
                >
                  <FetchButton danger>删除</FetchButton>
                </Popconfirm>
              ) : (
                ''
              )}
            </Authorization>
          </Space>
        );
      },
    },
  ];

  // 获取接口资源列表
  function getRows(data?: ReqAdminApiList) {
    setLoading(true);
    adminAPIList(data)
      .then((res) => {
        const data: RespAdminApiListData = res.data;
        const rows = data?.list || [];
        const total = data?.total ?? 0
        setRowsData(rows);
        setPageInfo((pageInfo) => ({ ...pageInfo, total }))
      })
      .catch((err) => {
        console.log('error', err);
      })
      .finally(() => {
        setLoading(false);
      });
  }

  // 接口资源状态更新
  function updateEnabled(record: AdminApiItem) {
    const updateData: ReqAdminApiEnable = {
      id: record.id,
      enabled: !record.isEnabled,
    };
    adminAPIEnable(updateData).then((res) => {
      message.success(res.msg, MessageDuritain, () => {
        getRows({ ...form.getFieldsValue() });
      });
    });
  }

  // 接口资源添加
  function openAddModal() {
    setAddModalStatus(true);
  }

  // 接口资源详情
  function openDetailModal(record: AdminApiItem) {
    adminAPIDetail({ id: record.id }).then((res) => {
      setDetailData(res.data);
      setDetailModalStatus(true);
    });
  }

  // 接口资源编辑
  function openEditModal(record: AdminApiItem) {
    adminAPIDetail({ id: record.id }).then((res) => {
      setDetailData(res.data);
      setEditModalStatus(true);
    });
  }

  function noticeAddModal(data: NoticeModalPropsType) {
    setAddModalStatus(false);
    if (data.reload) {
      getRows({ ...form.getFieldsValue() });
    }
  }

  function noticeDetailModal(data: NoticeModalPropsType) {
    setDetailData(undefined);
    setDetailModalStatus(false);
    if (data.reload) {
      getRows({ ...form.getFieldsValue() });
    }
  }

  function noticeEditModal(data: NoticeModalPropsType) {
    setDetailData(undefined);
    setEditModalStatus(false);
    if (data.reload) {
      getRows({ ...form.getFieldsValue() });
    }
  }

  // 删除接口资源
  function onDelete(record: AdminApiItem) {
    adminAPIDelete({ id: record.id }).then((res) => {
      message.success(res.msg, MessageDuritain);
      getRows({ ...form.getFieldsValue() });
    });
  }
  // 列表搜索
  function onSearchFinish(values: ReqAdminApiList) {
    const base = handlePagination(1, pageInfo.pageSize)
    getRows({ ...values, base });
  }

  // 搜索重置
  function onSearchReset() {
    form.resetFields();
    setPageInfo(searchResetPageInfo(pageInfo.pageSize))
    const base = handlePagination(1, pageInfo.pageSize)
    getRows({ base });
  }

  function onShowSizeChange(current: number, size: number) {
    const page = { ...pageInfo, pageSize: size, pageNum: current }
    setPageInfo(() => ({ ...page }));
  }

  function tableChange(pagination: any, filters: any, sorter: any) {
    const page = handlePagination(pagination.current, pagination.pageSize)
    setPageInfo({ ...pageInfo, ...page });
    const base = { ...page, sortField: sorter.field, sortType: sorter.order, }
    getRows({
      ...form.getFieldsValue(),
      base,
    });
  }

  useEffect(() => {
    onSearchReset();
  }, []);

  return (
    <Container>
      <Search>
        <Form form={form} onFinish={onSearchFinish}>
          <Row gutter={FormSearchRowGutter}>
            <Col span={FormSearchRowColSpan}>
              <Form.Item label="名称" name="name" initialValue={''}>
                <Input />
              </Form.Item>
            </Col>
            <Col span={FormSearchRowColSpan}>
              <Form.Item label="路由" name="path" initialValue={''}>
                <Input />
              </Form.Item>
            </Col>
            <Col span={FormSearchRowColSpan}>
              <Form.Item label="键名" name="key" initialValue={''}>
                <Input />
              </Form.Item>
            </Col>
            <Col span={FormSearchRowColSpan}>
              <Form.Item label="状态" name="enabled" initialValue={0}>
                <Select style={{ offset: 0, width: '120' }}>
                  <Select.Option value={0}>全部</Select.Option>
                  <Select.Option value={1}>启用</Select.Option>
                  <Select.Option value={2}>禁用</Select.Option>
                </Select>
              </Form.Item>
            </Col>
          </Row>
          <Row>
            <Col span={24} style={{ textAlign: 'right' }}>
              <Space>
                <Button type="primary" htmlType="submit">
                  <SearchOutlined />
                  查询
                </Button>
                <Button type="primary" htmlType="button" onClick={onSearchReset}>
                  <ReloadOutlined />
                  清除
                </Button>
              </Space>
            </Col>
          </Row>
        </Form>
      </Search>

      <Content>
        {/* button */}
        <Space style={{ marginBottom: '1rem' }}>
          <Authorization name="AdminApiEdit">
            <Button type="primary" onClick={openAddModal}>
              <PlusOutlined />
              新建接口
            </Button>
          </Authorization>
        </Space>

        {/* table */}
        <Table
          sticky
          rowKey="id"
          scroll={{ x: 'auto' }}
          loading={loading}
          columns={columns}
          dataSource={rowsData}
          onChange={tableChange}
          pagination={{
            current: pageInfo.pageNum,
            pageSize: pageInfo.pageSize,
            total: pageInfo.total,
            onShowSizeChange,
            ...DefaultPagination,
          }}
        />
      </Content>

      {/* modal */}

      <AdminAPIAddModal modalStatus={addModalStatus} noticeModal={noticeAddModal} />

      {detailData ? (
        <>
          <AdminAPIDetailModal
            modalStatus={detailModalStatus}
            detailData={detailData}
            noticeModal={noticeDetailModal}
          />
          <AdminAPIEditModal
            modalStatus={editModalStatus}
            detailData={detailData}
            noticeModal={noticeEditModal}
          />
        </>
      ) : (
        <></>
      )}
    </Container>
  );
};

export default Admin;

// admin-vue3x/src/views/admin/api/index.vue
<template>
  <PageContainer title="接口管理" :page-info="pageInfo" @page-change="onPageChange" @page-size-change="onPageSizeChange">
    <template #searchArea>
      <a-form layout="inline" :model="searchForm" class="search-form" @finish="onSearch">
        <a-form-item label="唯一键" name="key">
          <a-input v-model:value="searchForm.key" placeholder="请输入唯一键" allow-clear />
        </a-form-item>
        <a-form-item label="名称" name="name">
          <a-input v-model:value="searchForm.name" placeholder="请输入接口名称" allow-clear />
        </a-form-item>
        <a-form-item label="路径" name="path">
          <a-input v-model:value="searchForm.path" placeholder="请输入接口路径" allow-clear />
        </a-form-item>
        <a-form-item>
          <a-space>
            <a-button type="primary" html-type="submit">
              <template #icon><SearchOutlined /></template>
              查询
            </a-button>
            <a-button @click="onReset">
              <template #icon><ReloadOutlined /></template>
              重置
            </a-button>
          </a-space>
        </a-form-item>
      </a-form>
    </template>
    <template #extra>
      <a-button type="primary" @click="openAddModal">
        <template #icon><PlusOutlined /></template>
        新建接口
      </a-button>
    </template>

    <a-table
      :columns="columns"
      :data-source="rows"
      :loading="loading"
      :pagination="false"
      row-key="id"
      :scroll="{ x: 1000 }"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'isEnabled'">
          <a-popconfirm
            :title="`确定要${record.isEnabled ? '禁用' : '启用'}该接口吗？`"
            ok-text="确定"
            cancel-text="取消"
            @confirm="updateEnabled(record)"
          >
            <RowEnabledButton :is-enabled="record.isEnabled" />
          </a-popconfirm>
        </template>
        <template v-else-if="column.key === 'action'">
          <a-space>
            <Authorization permission="AdminApiView">
              <a-button type="link" size="small" @click="openDetailModal(record)">详情</a-button>
            </Authorization>
            <Authorization permission="AdminApiEdit">
              <a-button type="link" size="small" @click="openEditModal(record)">编辑</a-button>
            </Authorization>
            <Authorization permission="AdminApiDelete">
              <a-popconfirm
                v-if="!record.isEnabled"
                title="确定要删除该接口吗？"
                ok-text="确定"
                cancel-text="取消"
                @confirm="onDelete(record)"
              >
                <a-button type="link" size="small" danger>删除</a-button>
              </a-popconfirm>
            </Authorization>
          </a-space>
        </template>
      </template>
    </a-table>

    <AddApiModal v-model:open="addModalStatus" @notice="onModalNotice" />
    <EditApiModal v-model:open="editModalStatus" :detail-data="editData" @notice="onModalNotice" />
    <DetailApiDrawer v-model:open="detailModalStatus" :detail-data="detailData" />
  </PageContainer>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { message } from 'ant-design-vue';
import { SearchOutlined, ReloadOutlined, PlusOutlined } from '@ant-design/icons-vue';
import PageContainer from '@/components/PageContainer.vue';
import Authorization from '@/components/Authorization.vue';
import RowEnabledButton from '@/components/RowEnabledButton.vue';
import AddApiModal from './components/AddApiModal.vue';
import EditApiModal from './components/EditApiModal.vue';
import DetailApiDrawer from './components/DetailApiDrawer.vue';
import { getAdminApiList, deleteAdminApi, enableAdminApi } from '@/api/admin/api';
import type { AdminApiItem } from '@/types/common';
import { DEFAULT_PAGE_INFO } from '@/api/config';
import type { PageInfoType } from '@/api/types';

const loading = ref(false);
const rows = ref<AdminApiItem[]>([]);
const pageInfo = reactive<PageInfoType>({ ...DEFAULT_PAGE_INFO });

const searchForm = reactive<{ key?: string; name?: string; path?: string }>({
  key: undefined,
  name: undefined,
  path: undefined,
});

const addModalStatus = ref(false);
const editModalStatus = ref(false);
const detailModalStatus = ref(false);
const editData = ref<AdminApiItem>();
const detailData = ref<AdminApiItem>();

const columns = [
  { title: 'ID', dataIndex: 'id', key: 'id', fixed: 'left', width: 80 },
  { title: '接口名称', dataIndex: 'name', key: 'name', width: 160 },
  { title: '唯一键', dataIndex: 'key', key: 'key', width: 200 },
  { title: '接口路径', dataIndex: 'path', key: 'path', width: 240 },
  { title: '状态', dataIndex: 'isEnabled', key: 'isEnabled', width: 100 },
  { title: '创建时间', dataIndex: 'createdAt', key: 'createdAt', width: 180 },
  { title: '更新时间', dataIndex: 'updatedAt', key: 'updatedAt', width: 180 },
  { title: '操作', dataIndex: 'action', key: 'action', fixed: 'right', width: 200 },
];

function getRows() {
  loading.value = true;
  getAdminApiList({
    pageNum: pageInfo.pageNum,
    pageSize: pageInfo.pageSize,
    key: searchForm.key,
    name: searchForm.name,
    path: searchForm.path,
  })
    .then((res) => {
      rows.value = res.data.list || [];
      pageInfo.total = res.data.pageInfo?.total || 0;
    })
    .finally(() => {
      loading.value = false;
    });
}

function onSearch() {
  if (pageInfo.pageNum !== 1) {
    pageInfo.pageNum = 1;
    getRows();
  } else {
    getRows();
  }
}

function onReset() {
  searchForm.key = undefined;
  searchForm.name = undefined;
  searchForm.path = undefined;
  onSearch();
}

function onPageChange(pageNum: number) {
  pageInfo.pageNum = pageNum;
  getRows();
}

function onPageSizeChange(pageSize: number) {
  pageInfo.pageSize = pageSize;
  pageInfo.pageNum = 1;
  getRows();
}

function updateEnabled(record: AdminApiItem) {
  enableAdminApi({ id: record.id, enabled: !record.isEnabled }).then((res) => {
    message.success(res.msg, 2);
    getRows();
  });
}

function onDelete(record: AdminApiItem) {
  deleteAdminApi({ id: record.id }).then((res) => {
    message.success(res.msg, 2);
    getRows();
  });
}

function openAddModal() {
  addModalStatus.value = true;
}

function openEditModal(record: AdminApiItem) {
  editData.value = record;
  editModalStatus.value = true;
}

function openDetailModal(record: AdminApiItem) {
  detailData.value = record;
  detailModalStatus.value = true;
}

function onModalNotice() {
  getRows();
}

onMounted(() => {
  getRows();
});
</script>

<style scoped lang="less">
.search-form {
  .ant-form-item {
    margin-bottom: 8px;
  }
}
</style>
