// admin-react/src/components/HeaderRight.tsx
import { useNavigate } from 'react-router-dom';
import { Avatar, Dropdown, message } from 'antd';
import type { MenuProps } from 'antd';
import { UserOutlined, LogoutOutlined } from '@ant-design/icons';
import { useUserStore } from '@/store/user';
import { LoginPath } from '@/api/config';

/** 头部右侧：账号下拉（个人中心 / 退出登录） */
export default function HeaderRight() {
  const navigate = useNavigate();
  const userInfo = useUserStore((s) => s.userInfo);
  const logoutAsync = useUserStore((s) => s.logoutAsync);

  const items: MenuProps['items'] = [
    { key: 'account', icon: <UserOutlined />, label: '个人中心' },
    { type: 'divider' },
    { key: 'logout', icon: <LogoutOutlined />, label: '退出登录' },
  ];

  const onClick: MenuProps['onClick'] = async ({ key }) => {
    if (key === 'account') {
      navigate('/account');
      return;
    }
    if (key === 'logout') {
      await logoutAsync();
      message.success('退出登录成功');
      navigate(LoginPath);
    }
  };

  const displayName = userInfo?.nickname || userInfo?.username;

  return (
    <div className="header-right">
      <Dropdown menu={{ items, onClick }} placement="bottomRight">
        <div className="account">
          <Avatar src={userInfo?.avatar} size={28} className="avatar">
            {(displayName || '?')[0]}
          </Avatar>
          <span className="name">{displayName}</span>
        </div>
      </Dropdown>
    </div>
  );
}

// admin-vue3x/src/components/HeaderRight.vue
<template>
  <div class="header-right">
    <a-dropdown placement="bottomRight">
      <div class="account">
        <a-avatar :src="store.userInfo?.avatar" :size="28" class="avatar">
          {{ (store.userInfo?.nickname || store.userInfo?.username || '?')[0] }}
        </a-avatar>
        <span class="name">{{ store.userInfo?.nickname || store.userInfo?.username }}</span>
      </div>
      <template #overlay>
        <a-menu @click="onMenuClick">
          <a-menu-item key="account">
            <UserOutlined />
            个人中心
          </a-menu-item>
          <a-menu-divider />
          <a-menu-item key="logout">
            <LogoutOutlined />
            退出登录
          </a-menu-item>
        </a-menu>
      </template>
    </a-dropdown>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import { UserOutlined, LogoutOutlined } from '@ant-design/icons-vue';
import { message } from 'ant-design-vue';
import { useUserStore } from '@/store/user';
import { LoginPath } from '@/api/config';

const router = useRouter();
const store = useUserStore();

const onMenuClick = async ({ key }: { key: string }) => {
  if (key === 'account') {
    router.push('/account');
  } else if (key === 'logout') {
    await store.logoutAsync();
    message.success('退出登录成功');
    router.push(LoginPath);
  }
};
</script>

<style scoped lang="less">
.header-right {
  .account {
    display: flex;
    align-items: center;
    cursor: pointer;

    .avatar {
      background: #1677ff;
    }

    .name {
      margin-left: 8px;
      color: rgba(0, 0, 0, 0.85);
    }
  }
}
</style>
