// admin-react/src/components/RowEnabledButton.tsx
import { Switch } from 'antd';

interface RowEnabledButtonProps {
  isEnabled?: boolean;
  isEnabledButtonDisabled?: boolean;
  onChange?: (checked: boolean) => void;
}

/** 列表行的启用/禁用开关 */
export default function RowEnabledButton({
  isEnabled,
  isEnabledButtonDisabled,
  onChange,
}: RowEnabledButtonProps) {
  return (
    <Switch
      checked={isEnabled}
      disabled={isEnabledButtonDisabled}
      checkedChildren="启用"
      unCheckedChildren="禁用"
      onChange={onChange}
    />
  );
}

// admin-vue3x/src/components/RowEnabledButton.vue
<template>
  <a-switch
    :checked="isEnabled"
    :disabled="isEnabledButtonDisabled"
    checked-children="启用"
    un-checked-children="禁用"
    @change="onChange"
  />
</template>

<script setup lang="ts">
defineProps<{
  isEnabled?: boolean;
  isEnabledButtonDisabled?: boolean;
}>();

const emit = defineEmits<{
  (e: 'change', checked: boolean): void;
}>();

const onChange = (checked: boolean) => {
  emit('change', checked);
};
</script>
