// admin-react/src/components/SiderMenu.tsx
import { useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Menu } from 'antd';
import type { MenuProps } from 'antd';
import { useUserStore } from '@/store/user';
import { getAntIcon } from '@/utils/icon';
import { HandleRemoteMenuIntoLocal, localMenuData, type MenuConfigItem } from '@/router/menu';
import { HomePath } from '@/api/config';

type MenuItem = Required<MenuProps>['items'][number];

/** 渲染菜单标题：有图标显示图标，无图标占位保持对齐 */
function renderTitle(name: string, icon?: string) {
  const Icon = getAntIcon(icon);
  return (
    <>
      {Icon ? <Icon /> : <span className="menu-icon-placeholder" aria-hidden="true" />}
      <span>{name}</span>
    </>
  );
}

function toMenuItems(list: MenuConfigItem[]): MenuItem[] {
  return list.map((item) => {
    if (!item.children || item.children.length === 0) {
      return { key: item.key, icon: <></>, label: renderTitle(item.name, item.icon) };
    }
    return {
      key: item.key,
      label: renderTitle(item.name, item.icon),
      children: toMenuItems(item.children),
    };
  });
}

/** 侧边菜单：本地菜单配置 + 后端返回的菜单过滤 */
export default function SiderMenu({ collapsed, onNavigate }: { collapsed: boolean; onNavigate?: () => void }) {
  const navigate = useNavigate();
  const location = useLocation();
  const menus = useUserStore((s) => s.menus);

  const menuItems = useMemo<MenuConfigItem[]>(() => {
    const remoteMenus = menus || {};
    const result = HandleRemoteMenuIntoLocal([], localMenuData, remoteMenus, 'children');
    // 顶部固定“首页”
    const homeItem: MenuConfigItem = { key: 'Home', path: HomePath, name: '首页', icon: 'HomeOutlined' };
    return [homeItem, ...result];
  }, [menus]);

  const items = useMemo(() => toMenuItems(menuItems), [menuItems]);

  // 当前选中项：按路径匹配
  const selectedKeys = useMemo(() => {
    const hit = menuItems.find((item) => item.path === location.pathname);
    if (hit) return [hit.key];
    const child = menuItems
      .flatMap((item) => item.children ?? [])
      .find((item) => item.path === location.pathname);
    return child ? [child.key] : [];
  }, [menuItems, location.pathname]);

  // 默认展开当前菜单所在分组
  const [openKeys, setOpenKeys] = useState<string[]>(() => {
    const parent = menuItems.find((item) => item.children?.some((child) => child.path === location.pathname));
    return parent ? [parent.key] : [];
  });

  const onClick: MenuProps['onClick'] = ({ key }) => {
    const hit =
      menuItems.find((item) => item.key === key) ??
      menuItems.flatMap((item) => item.children ?? []).find((item) => item.key === key);
    if (hit) {
      navigate(hit.path);
      onNavigate?.();
    }
  };

  return (
    <div className="sider-menu">
      <div className="logo" onClick={() => navigate(HomePath)}>
        <img src="https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg" alt="logo" />
        {!collapsed && <span>Admin React</span>}
      </div>
      <Menu
        theme="dark"
        mode="inline"
        items={items}
        selectedKeys={selectedKeys}
        openKeys={openKeys}
        onOpenChange={(keys) => setOpenKeys(keys as string[])}
        onClick={onClick}
      />
    </div>
  );
}

// admin-vue3x/src/components/SiderMenu.vue
<template>
  <div class="sider-menu">
    <div class="logo" @click="router.push('/home')">
      <img
        src="https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg"
        alt="logo"
      />
      <span v-show="!collapsed">Admin Vue3x</span>
    </div>
    <a-menu
      theme="dark"
      mode="inline"
      :selected-keys="selectedKeys"
      :open-keys="openKeys"
      @click="onMenuClick"
      @openChange="onOpenChange"
    >
      <template v-for="item in menuItems" :key="item.key">
        <a-menu-item v-if="!item.children || item.children.length === 0" :key="item.key">
          <router-link :to="item.path">
            <component :is="menuIcon(item.icon)" v-if="menuIcon(item.icon)" />
            <span v-else class="menu-icon-placeholder" aria-hidden="true"></span>
            <span>{{ item.name }}</span>
          </router-link>
        </a-menu-item>
        <a-sub-menu v-else :key="item.key">
          <template #title>
            <component :is="menuIcon(item.icon)" v-if="menuIcon(item.icon)" />
            <span v-else class="menu-icon-placeholder" aria-hidden="true"></span>
            <span>{{ item.name }}</span>
          </template>
          <a-menu-item v-for="child in item.children" :key="child.key">
            <router-link :to="child.path">
              <component :is="menuIcon(child.icon)" v-if="menuIcon(child.icon)" />
              <span v-else class="menu-icon-placeholder" aria-hidden="true"></span>
              <span>{{ child.name }}</span>
            </router-link>
          </a-menu-item>
        </a-sub-menu>
      </template>
    </a-menu>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useUserStore } from '@/store/user';
import { getAntIcon } from '@/utils/icon';
import { HandleRemoteMenuIntoLocal, localMenuData, type MenuConfigItem } from '@/router/menu';
import { HomePath } from '@/api/config';

defineProps<{ collapsed: boolean }>();

const route = useRoute();
const router = useRouter();
const store = useUserStore();

/** 按名称取图标组件，支持菜单管理中配置的任意 ant 图标 */
function menuIcon(name?: string) {
  return getAntIcon(name);
}

/** 根据远程菜单过滤本地菜单 */
const menuItems = computed<MenuConfigItem[]>(() => {
  const remoteMenus = store.menus || {};
  let result: MenuConfigItem[] = HandleRemoteMenuIntoLocal([], localMenuData, remoteMenus, 'children');
  // 顶部固定“首页”
  const homeItem: MenuConfigItem = { key: 'Home', path: HomePath, name: '首页', icon: 'HomeOutlined' };
  result = [homeItem, ...result];
  return result;
});

const selectedKeys = computed(() => [String(route.name || '')]);
const openKeys = ref<string[]>([]);

watch(
  () => route.path,
  (path) => {
    // 自动展开当前菜单所在分组
    for (const item of menuItems.value) {
      if (item.children?.some((child) => child.path === path)) {
        if (!openKeys.value.includes(item.key)) {
          openKeys.value = [item.key];
        }
        break;
      }
    }
  },
  { immediate: true },
);

const onMenuClick = ({ key }: { key: string }) => {
  const item = menuItems.value.find((i) => i.key === key);
  if (item) {
    router.push(item.path);
  }
};

const onOpenChange = (keys: string[]) => {
  openKeys.value = keys as string[];
};
</script>

<style scoped lang="less">
.sider-menu {
  height: 100%;

  // 无图标时占位，保持与有图标菜单的文本对齐
  .menu-icon-placeholder {
    display: inline-block;
    flex: none;
    width: 16px;
    margin-right: 10px;
  }

  .logo {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 64px;
    color: #fff;
    font-size: 18px;
    font-weight: 600;
    cursor: pointer;

    img {
      width: 32px;
      height: 32px;
      margin-right: 8px;
    }
  }
}
</style>
