// admin-react/src/components/TabsView.tsx
import { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Dropdown, Tabs } from 'antd';
import type { MenuProps } from 'antd';
import { CloseOutlined, ColumnWidthOutlined, MinusOutlined } from '@ant-design/icons';
import { HomePath } from '@/api/config';
import { getRouteTitle } from '@/router/menu';
import { useTabsStore } from '@/store/tabs';

/** 多页签：路由变化时同步，支持右键关闭当前/其他/全部 */
export default function TabsView() {
  const navigate = useNavigate();
  const location = useLocation();
  const tabs = useTabsStore((s) => s.tabs);
  const addTab = useTabsStore((s) => s.addTab);
  const removeTab = useTabsStore((s) => s.removeTab);
  const removeOther = useTabsStore((s) => s.removeOther);
  const removeAll = useTabsStore((s) => s.removeAll);
  const getNeighborPath = useTabsStore((s) => s.getNeighborPath);

  const [activeKey, setActiveKey] = useState(location.pathname);

  // 路由变化时同步页签（不存在则新增，标题取对应菜单名称）
  useEffect(() => {
    setActiveKey(location.pathname);
    addTab({
      path: location.pathname,
      title: getRouteTitle(location.pathname),
      closable: location.pathname !== HomePath,
    });
  }, [location.pathname, addTab]);

  const closeTab = (path: string) => {
    const nextPath = getNeighborPath(path, location.pathname);
    removeTab(path);
    if (nextPath) navigate(nextPath);
  };

  const onMenuClick = (key: string, path: string) => {
    if (key === 'current') {
      closeTab(path);
      return;
    }
    if (key === 'other') {
      removeOther(path);
      if (location.pathname !== path) navigate(path);
      return;
    }
    if (key === 'all') {
      removeAll();
      if (location.pathname !== HomePath) navigate(HomePath);
    }
  };

  const items: MenuProps['items'] = [
    { key: 'current', icon: <CloseOutlined />, label: '关闭当前' },
    { key: 'other', icon: <ColumnWidthOutlined />, label: '关闭其他' },
    { key: 'all', icon: <MinusOutlined />, label: '关闭全部' },
  ];

  return (
    <div className="tabs-view">
      <Tabs
        activeKey={activeKey}
        type="editable-card"
        hideAdd
        size="small"
        className="tabs"
        onChange={(key) => {
          if (key !== location.pathname) navigate(key);
        }}
        onEdit={(targetKey, action) => {
          if (action === 'remove') closeTab(String(targetKey));
        }}
        items={tabs.map((tab) => ({
          key: tab.path,
          closable: tab.closable,
          label: (
            <Dropdown menu={{ items, onClick: ({ key }) => onMenuClick(String(key), tab.path) }} trigger={['contextMenu']}>
              <span className="tab-title">{getRouteTitle(tab.path)}</span>
            </Dropdown>
          ),
        }))}
      />
    </div>
  );
}

// admin-vue3x/src/components/TabsView.vue
<template>
  <div class="tabs-view">
    <a-tabs
      v-model:active-key="activeKey"
      type="editable-card"
      hide-add
      size="small"
      class="tabs"
      @edit="onEdit"
      @change="onChange"
    >
      <a-tab-pane v-for="tab in tabs" :key="tab.path" :closable="tab.closable">
        <template #tab>
          <a-dropdown :trigger="['contextmenu']">
            <span class="tab-title">{{ tab.title }}</span>
            <template #overlay>
              <a-menu @click="({ key }) => onMenuClick(String(key), tab.path)">
                <a-menu-item key="current" :disabled="!tab.closable">
                  <template #icon><CloseOutlined /></template>
                  关闭当前
                </a-menu-item>
                <a-menu-item key="other">
                  <template #icon><ColumnWidthOutlined /></template>
                  关闭其他
                </a-menu-item>
                <a-menu-item key="all">
                  <template #icon><MinusOutlined /></template>
                  关闭全部
                </a-menu-item>
              </a-menu>
            </template>
          </a-dropdown>
        </template>
      </a-tab-pane>
    </a-tabs>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { CloseOutlined, ColumnWidthOutlined, MinusOutlined } from '@ant-design/icons-vue';
import { HomePath } from '@/api/config';
import { useTabsStore } from '@/store/tabs';

const route = useRoute();
const router = useRouter();
const tabsStore = useTabsStore();

const tabs = computed(() => tabsStore.tabs);
const activeKey = ref(route.path);

// 路由变化（点击菜单/切换页签/前进后退）时同步页签，不存在则新增
watch(
  () => route.path,
  (path) => {
    activeKey.value = path;
    tabsStore.addTab({
      path,
      title: (route.meta?.title as string) || String(route.name ?? path),
      closable: path !== HomePath,
    });
  },
  { immediate: true },
);

function onChange(key: string | number) {
  const path = String(key);
  if (path !== route.path) {
    router.push(path);
  }
}

function onEdit(targetKey: string | number, action: string) {
  if (action === 'remove') {
    closeTab(String(targetKey));
  }
}

function closeTab(path: string) {
  const nextPath = tabsStore.getNeighborPath(path, route.path);
  tabsStore.removeTab(path);
  if (nextPath) {
    router.push(nextPath);
  }
}

function onMenuClick(key: string, path: string) {
  if (key === 'current') {
    closeTab(path);
    return;
  }
  if (key === 'other') {
    tabsStore.removeOther(path);
    if (route.path !== path) {
      router.push(path);
    }
    return;
  }
  if (key === 'all') {
    tabsStore.removeAll();
    if (route.path !== HomePath) {
      router.push(HomePath);
    }
  }
}
</script>

<style scoped lang="less">
.tabs-view {
  padding: 6px 8px 0;
  margin-bottom: 8px;
  background: #fff;
  border-radius: 2px;

  .tab-title {
    user-select: none;
  }

  :deep(.ant-tabs-nav) {
    margin-bottom: 0;
  }
}
</style>
