// admin-react/src/views/error/404.tsx
import { useNavigate } from 'react-router-dom';
import { Button, Result } from 'antd';
import { HomePath } from '@/api/config';

/** 404 页面不存在 */
export default function NotFound() {
  const navigate = useNavigate();
  return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh' }}>
      <Result
        status="404"
        title="404"
        subTitle="抱歉，您访问的页面不存在"
        extra={
          <Button type="primary" onClick={() => navigate(HomePath, { replace: true })}>
            返回首页
          </Button>
        }
      />
    </div>
  );
}

// admin-vue3x/src/views/error/404.vue
<template>
  <div class="error-page">
    <a-result status="404" title="404" sub-title="抱歉，您访问的页面不存在">
      <template #extra>
        <a-button type="primary" @click="goHome">返回首页</a-button>
      </template>
    </a-result>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import { HomePath } from '@/api/config';

const router = useRouter();

function goHome() {
  router.replace(HomePath);
}
</script>

<style scoped lang="less">
.error-page {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100vh;
}
</style>
