// admin-vue3x/src/views/home/index.vue
<template>
  <div class="home-page">
    <a-card title="排班日历">
      <a-calendar v-model:value="currentDate" fullscreen>
        <template #dateCellRender="{ current }">
          <ul class="events">
            <li v-if="current.date() === today.date()" class="event-today">
              <a-tag color="blue">今日无排班计划</a-tag>
            </li>
          </ul>
        </template>
      </a-calendar>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import dayjs, { type Dayjs } from 'dayjs';

const today = dayjs();
const currentDate = ref<Dayjs>(dayjs());
</script>

<style scoped lang="less">
.home-page {
  .events {
    margin: 0;
    padding: 0;
    list-style: none;

    .event-today {
      margin-top: 4px;
    }
  }
}
</style>

// admin-react/src/views/home/index.tsx
import { useState } from 'react';
import { Card, Calendar, Tag } from 'antd';
import dayjs, { type Dayjs } from 'dayjs';

/** 首页：排班日历 */
export default function Home() {
  const today = dayjs();
  const [currentDate, setCurrentDate] = useState<Dayjs>(dayjs());

  return (
    <div className="home-page">
      <Card title="排班日历">
        <Calendar
          fullscreen
          value={currentDate}
          onChange={(v) => setCurrentDate(v as Dayjs)}
          cellRender={(current: Dayjs, info) => {
            if (info.type === 'date' && current.date() === today.date()) {
              return (
                <ul style={{ margin: 0, padding: 0, listStyle: 'none' }}>
                  <li style={{ marginTop: 4 }}>
                    <Tag color="blue">今日无排班计划</Tag>
                  </li>
                </ul>
              );
            }
            return info.originNode;
          }}
        />
      </Card>
    </div>
  );
}
