// admin-vue3x/src/views/error/403.vue
<template>
  <div class="error-page">
    <a-result status="403" title="403" sub-title="抱歉，您没有权限访问该页面">
      <template #extra>
        <a-button type="primary" @click="goHome">返回首页</a-button>
      </template>
    </a-result>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import { HomePath } from '@/api/config';

const router = useRouter();

function goHome() {
  router.replace(HomePath);
}
</script>

<style scoped lang="less">
.error-page {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100vh;
}
</style>

// admin-react/src/views/error/403.tsx
import { useNavigate } from 'react-router-dom';
import { Button, Result } from 'antd';
import { HomePath } from '@/api/config';

/** 403 无权限页 */
export default function Forbidden() {
  const navigate = useNavigate();
  return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh' }}>
      <Result
        status="403"
        title="403"
        subTitle="抱歉，您没有权限访问该页面"
        extra={
          <Button type="primary" onClick={() => navigate(HomePath, { replace: true })}>
            返回首页
          </Button>
        }
      />
    </div>
  );
}
